"""Style system for subtitle rendering."""

from dataclasses import dataclass, field, asdict
from typing import Dict, Any, Optional


def hex_to_ass_color(hex_color: str) -> str:
    """Convert hex color to ASS color format.

    Args:
        hex_color: '#RRGGBB' or '#AARRGGBB'

    Returns:
        ASS color string '&HAABBGGRR'
    """
    h = hex_color.lstrip('#')
    if len(h) == 6:
        r, g, b = h[0:2], h[2:4], h[4:6]
        return f"&H00{b.upper()}{g.upper()}{r.upper()}"
    elif len(h) == 8:
        a, r, g, b = h[0:2], h[2:4], h[4:6], h[6:8]
        return f"&H{a.upper()}{b.upper()}{g.upper()}{r.upper()}"
    else:
        raise ValueError(f"Invalid hex color: {hex_color}")


@dataclass
class FontStyle:
    """Font style configuration."""

    font: str = "Arial"
    size: int = 60
    color: str = "#FFFFFF"
    bold: bool = False
    italic: bool = False
    outline: float = 3.0
    outline_color: str = "#000000"
    shadow: float = 1.0
    shadow_color: str = "#80000000"

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to dictionary."""
        return asdict(self)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "FontStyle":
        """Deserialize from dictionary."""
        return cls(**{k: v for k, v in data.items() if k in cls.__dataclass_fields__})


@dataclass
class StyleProfile:
    """Complete style profile for subtitle rendering."""

    name: str = "default"
    primary: FontStyle = field(default_factory=FontStyle)
    secondary: FontStyle = field(default_factory=lambda: FontStyle(
        size=45, color="#AAAAAA", outline=2.0
    ))
    alignment: int = 2
    margin_left: int = 10
    margin_right: int = 10
    margin_bottom: int = 30
    line_spacing: int = 0
    play_res_x: int = 1920
    play_res_y: int = 1080

    def to_ass_header(self) -> str:
        """Generate complete [Script Info] + [V4+ Styles] header."""
        p = self.primary
        s = self.secondary
        p_color = hex_to_ass_color(p.color)
        p_outline = hex_to_ass_color(p.outline_color)
        p_shadow = hex_to_ass_color(p.shadow_color)
        s_color = hex_to_ass_color(s.color)
        s_outline = hex_to_ass_color(s.outline_color)
        s_shadow = hex_to_ass_color(s.shadow_color)

        return (
            f"[Script Info]\n"
            f"Title: Generated by SubGen\n"
            f"ScriptType: v4.00+\n"
            f"PlayResX: {self.play_res_x}\n"
            f"PlayResY: {self.play_res_y}\n"
            f"WrapStyle: 0\n"
            f"\n"
            f"[V4+ Styles]\n"
            f"Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, "
            f"OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, "
            f"ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, "
            f"Alignment, MarginL, MarginR, MarginV, Encoding\n"
            f"Style: Default,{p.font},{p.size},{p_color},&H000000FF,"
            f"{p_outline},{p_shadow},{int(p.bold)},{int(p.italic)},0,0,"
            f"100,100,0,0,1,{p.outline},{p.shadow},{self.alignment},"
            f"{self.margin_left},{self.margin_right},{self.margin_bottom},1\n"
            f"Style: Secondary,{s.font},{s.size},{s_color},&H000000FF,"
            f"{s_outline},{s_shadow},{int(s.bold)},{int(s.italic)},0,0,"
            f"100,100,0,0,1,{s.outline},{s.shadow},{self.alignment},"
            f"{self.margin_left},{self.margin_right},{self.margin_bottom + 50},1\n"
            f"\n"
            f"[Events]\n"
            f"Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text"
        )

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to dictionary."""
        return {
            "name": self.name,
            "primary": self.primary.to_dict(),
            "secondary": self.secondary.to_dict(),
            "alignment": self.alignment,
            "margin_left": self.margin_left,
            "margin_right": self.margin_right,
            "margin_bottom": self.margin_bottom,
            "line_spacing": self.line_spacing,
            "play_res_x": self.play_res_x,
            "play_res_y": self.play_res_y,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "StyleProfile":
        """Deserialize from dictionary."""
        d = dict(data)
        if "primary" in d and isinstance(d["primary"], dict):
            d["primary"] = FontStyle.from_dict(d["primary"])
        if "secondary" in d and isinstance(d["secondary"], dict):
            d["secondary"] = FontStyle.from_dict(d["secondary"])
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})


PRESETS: Dict[str, StyleProfile] = {
    "default": StyleProfile(),
    "netflix": StyleProfile(
        name="netflix",
        primary=FontStyle(font="Netflix Sans", size=55, color="#FFFFFF", outline=2.0, shadow=0.0, shadow_color="#00000000"),
        secondary=FontStyle(font="Netflix Sans", size=40, color="#CCCCCC", outline=1.5, shadow=0.0, shadow_color="#00000000"),
        margin_bottom=40,
    ),
    "fansub": StyleProfile(
        name="fansub",
        primary=FontStyle(font="方正准圆_GBK", size=65, color="#00FFFF", bold=True, outline=3.0, shadow=1.5),
        secondary=FontStyle(font="Arial", size=45, color="#FFFFFF", outline=2.0, shadow=1.0),
        margin_bottom=25,
    ),
    "minimal": StyleProfile(
        name="minimal",
        primary=FontStyle(font="Helvetica", size=50, color="#FFFFFF", outline=1.0, shadow=0.0, shadow_color="#00000000"),
        secondary=FontStyle(font="Helvetica", size=38, color="#BBBBBB", outline=0.5, shadow=0.0, shadow_color="#00000000"),
        margin_bottom=20,
    ),
}


def load_style(config: Dict[str, Any]) -> StyleProfile:
    """Load style from config dict.

    Supports preset inheritance with partial overrides via config['styles'].

    Args:
        config: Configuration dictionary, optionally containing 'styles' block.

    Returns:
        StyleProfile instance.
    """
    styles_cfg = config.get("styles", {})
    if not styles_cfg:
        return StyleProfile()  # default

    preset_name = styles_cfg.get("preset", "default")
    base = PRESETS.get(preset_name, PRESETS["default"])
    base_dict = base.to_dict()

    # Apply overrides
    for key, value in styles_cfg.items():
        if key == "preset":
            continue
        if key in ("primary", "secondary") and isinstance(value, dict):
            base_dict[key].update(value)
        elif key in base_dict:
            base_dict[key] = value

    return StyleProfile.from_dict(base_dict)
